#!/bin/sh

set -o errexit -o nounset -o xtrace

main() {
  command=$1
  shift

  case $command in
  build)
    build "$@"
    ;;
  deploy)
    deploy "$@"
    ;;
  esac
}

build() {
  version=$1
  build_buf
  build_buf_build $version
}

deploy() {
  deploy_buf_build
}

build_buf() {
  pnpm exec buf lint || exit
  pnpm exec buf build || exit
}

build_buf_build() {
  version=$1
  echo $version >TAG_NAME
}

deploy_buf_build() {
  pnpm exec buf push --label $(cat TAG_NAME) --label main || exit
}

main "$@"
